name: Generate Snake

on:
  # Запуск каждые 24 часа
  schedule:
    - cron: "0 0 * * *"
  
  # Возможность запустить вручную из вкладки Actions
  workflow_dispatch:
  
  # Запуск при каждом пуше в ветку main
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Генерирует змейку из графа вкладов пользователя
      - name: generate-snake-game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}

          outputs: |
            dist/github-snake.svg
            dist/github-snake.svg?color_snake=pink&color_dots=fbcfe8,f472b6,ec4899,db2777,be185d
            dist/github-snake-dark.svg?color_snake=pink&color_dots=fbcfe8,f472b6,ec4899,db2777,be185d
